### ISSUE TITLE
关于跑bert时遇到的问题

### ISSUE THREAD

**Issue by 2Fgithub** [WHU-ZQH/KGAN#6]
跑的时候遇到这个：RuntimeError: CUDA error: device-side assert triggered
报一大串这种：/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [146,0,0], thread: [38,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
然后最后指向 squeeze_embedding 中的 x = x[x_sort_idx]

网上搜是说输入长度比Bert规定要大，请问应该怎么解决？

**Comment by UACurry** [comment]
请问解决了吗

**Comment by WHU-ZQH** [comment]
之前的代码在is_bert=1时可能存在问题，论文投稿时代码有所更新。更新后的代码和训练超参数会在近两天内发布，请耐心等待:)

**Comment by ewgfsd** [comment]
请问你解决了不？bert效果问题？
